apiVersion: v1
kind: Service
metadata:
  name: docs-analitics-monville-ext
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 30800
      targetPort: 30800
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: docs-analitics-monville-ext-manual
  namespace: monitoring
  labels:
    kubernetes.io/service-name: docs-analitics-monville-ext
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 30800
endpoints:
  - addresses:
      - "192.168.15.203"
