apiVersion: v1
kind: Service
metadata:
  name: pihole-ext
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: pihole-ext-manual
  namespace: monitoring
  labels:
    kubernetes.io/service-name: pihole-ext
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8080
endpoints:
  - addresses:
      - "192.168.15.100"
