apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zuno-app-registry
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-zuno-app-prod
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"https://ghcr.io":{"username":"{{ .GHCR_USERNAME }}","password":"{{ .GHCR_TOKEN }}","auth":"{{ printf "%s:%s" .GHCR_USERNAME .GHCR_TOKEN | b64enc }}"}}}
  data:
    - secretKey: GHCR_USERNAME
      remoteRef:
        key: GHCR_USERNAME
    - secretKey: GHCR_TOKEN
      remoteRef:
        key: GHCR_TOKEN
