apiVersion: v1
kind: Service
metadata:
  name: zuno-app-backend
spec:
  selector:
    app: zuno-app-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zuno-app-frontend
spec:
  selector:
    app: zuno-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
