apiVersion: v1
kind: Service
metadata:
  name: skull-backend
spec:
  selector:
    app: skull-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: skull-frontend
spec:
  selector:
    app: skull-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
