apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuno-app-backend
spec:
  template:
    spec:
      containers:
      - name: zuno-app-backend
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi
