apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuno-app

resources:
  - ../../base
  - clustersecretstore.yaml

replicas:
  - name: zuno-app-backend
    count: 1
  - name: zuno-app-frontend
    count: 1

patches:
  - path: frontend-service-patch.yaml
    target:
      kind: Service
      name: zuno-app-frontend
  - path: backend-resources-patch.yaml
    target:
      kind: Deployment
      name: zuno-app-backend
  - path: frontend-resources-patch.yaml
    target:
      kind: Deployment
      name: zuno-app-frontend
