apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuno-app

resources:
  - ../../base
  - clustersecretstore.yaml

images:
  - name: ghcr.io/zuno-webapp/zuno-be
    newTag: 63e82acc46b5ab2aa342aa125535869aa7925c35
  - name: ghcr.io/zuno-webapp/zuno-frontend
    newTag: 08798091a58fe78d6061dffc51b0250647feb1c9

replicas:
  - name: zuno-app-backend
    count: 1
  - name: zuno-app-frontend
    count: 1

patches:
  - path: frontend-service-patch.yaml
    target:
      kind: Service
      name: zuno-app-frontend
  - path: backend-resources-patch.yaml
    target:
      kind: Deployment
      name: zuno-app-backend
  - path: frontend-resources-patch.yaml
    target:
      kind: Deployment
      name: zuno-app-frontend
