apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuno-app

resources:
  - ../../base
  - clustersecretstore.yaml

images:
  - name: ghcr.io/zuno-webapp/zuno-be
    newTag: 3a165e66f8a75517930c5d48da27a8e464695ec5
  - name: ghcr.io/zuno-webapp/zuno-frontend
    newTag: 61e801193e29da16f937441b7263b0b4ffa131e2

replicas:
  - name: zuno-app-backend
    count: 1
  - name: zuno-app-frontend
    count: 1

patches:
  - path: frontend-service-patch.yaml
    target:
      kind: Service
      name: zuno-app-frontend
  - path: backend-resources-patch.yaml
    target:
      kind: Deployment
      name: zuno-app-backend
  - path: frontend-resources-patch.yaml
    target:
      kind: Deployment
      name: zuno-app-frontend
