apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-prod
  target:
    name: cloudflare-tunnel
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFLARE_TUNNEL_TOKEN
      remoteRef:
        key: /cloudflare/CLOUDFLARE_TUNNEL_TOKEN

