apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:whC88tSa7ABo9c7fGBVNQGez9UZQkbgzAUiSmrQOxg2OScofxxnWKi58ba16qJ4/manqWgI1J48f5BS0JFVZWtsg0ye57LCY1WJy+a0aSjbE0ouPf+yupuD17zX1RSOwqNNhVVWN+JPkJdFcv6wovUTQNOq1dydm+qG/2ypv5RTOi3/xb7xUNo7uI7Nv5wx9o90TDGCcYllQAAvYggKN60uZjSRhkIUj0elotTdeRNtfBptC3GjBqQ==,iv:PapGuLX/j7FQmbFohMJgx+CkVtPtnuyNaOKkkEftqIk=,tag:GJXxJlvjaTA4SpoWdm6Hww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fweajqxcxfygfurlpg6r9myu25fcrha0xxtaujwywskkaryewyas8hww9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTTgzQzNXZFNaT0E1d1cw
            eFk4SE5RQUFSUmVTYis4NXdBcWJEQklvbHdRCnREMXhXa3J1QjB6OURPY3hmcDhU
            ZUJEUUpsRnBNWEdVTmtYYzltZHNoelkKLS0tIFozSEhLMU9aWk5JTTNxb2pyVU5R
            Y2owdTJPWDNHWVF4OERxbHFGcWd5eGMK6p8USWlcU0p6yVP/eeidqron6eAHWEKg
            +gzUrvBDrSaj454NO8+z6lO9fDq4GpqYQdF4fBjE7IKpYhwlyg0iXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T15:28:00Z"
    mac: ENC[AES256_GCM,data:xkb2BfUgK2eEW/eebH7dFkSIjZYDLGMoDpPK9hpAqaKYs4pejrX8cOtOAEp4bllVCPc3IBdQjMJ3EXvGFfSybxFTov5L++roIjkDcgtOd+V9VwUvhyxEU0qaKScD9jTY5iwQaOw0aMHzHTuSKtZGv1dpneBpWnbZYuPKyoUtwj0=,iv:OBoR5O9tc0r5sgpGReJhjv5aKnG072dFmXwFXb8hVGw=,tag:b5BOE6iSFZNHbi2aRqa+wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
