apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joga-together-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-dev
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /joga-together-dev/SPRING_DATASOURCE_PASSWORD
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: /joga-together-dev/SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /joga-together-dev/SPRING_DATASOURCE_URL
    - secretKey: SPRING_MAIL_USERNAME
      sourceRef:
        storeRef:
          name: infisical-prod
          kind: ClusterSecretStore
      remoteRef:
        key: /joga-together/SPRING_MAIL_USERNAME
    - secretKey: SPRING_MAIL_PASSWORD
      sourceRef:
        storeRef:
          name: infisical-prod
          kind: ClusterSecretStore
      remoteRef:
        key: /joga-together/SPRING_MAIL_PASSWORD
    - secretKey: PROFILE_ENVIROMENT
      remoteRef:
        key: /joga-together-dev/PROFILE_ENVIROMENT
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /joga-together-dev/JWT_SECRET_KEY
