apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joga-together-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ojasonw/joga-together-backend
    newTag: dev
  - name: ojasonw/joga-together-web
    newTag: dev

replicas:
  - name: joga-together-backend
    count: 1
  - name: joga-together-frontend
    count: 1

patches:
  - path: externalsecret-patch.yaml
    target:
      kind: ExternalSecret
      name: joga-together-secrets
