apiVersion: v1
kind: Service
metadata:
  name: web-site-app
  namespace: web-site
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-site-app
  ports:
    - name: http
      port: 80
      targetPort: 80
