creation_rules:
  - path_regex: '.*secret.*\.yaml$'
    encrypted_regex: '^(data|stringData)$'
    age: age1fweajqxcxfygfurlpg6r9myu25fcrha0xxtaujwywskkaryewyas8hww9f
  - path_regex: '.*/alertmanager/.*configmap\.yaml$'
    encrypted_regex: '^(data)$'
    age: age1fweajqxcxfygfurlpg6r9myu25fcrha0xxtaujwywskkaryewyas8hww9f
