apiVersion: v1
kind: Service
metadata:
  name: docs-analitics-postgres
  namespace: monitoring
spec:
  selector:
    app: docs-analitics-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
