apiVersion: v1
kind: Service
metadata:
  name: docs-analitics-worker
  namespace: monitoring
spec:
  selector:
    app: docs-analitics-worker
  ports:
    - name: http
      port: 8000
      targetPort: 8000
