apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docs-analitics-medlivewell

resources:
  - ../../base

patches:
  - path: worker-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: docs-analitics-worker-config
