apiVersion: v1
kind: ConfigMap
metadata:
  name: docs-analitics-worker-config
data:
  CUSTOMER_TAG: "medlivewell"
  # Drive folder IDs do cliente Medlivewell (já existem no base — confirmar se são os corretos)
  DRIVE_FOLDER_PENDENTE: "1P3u6xqUEWMMv57lEdDNLhKH5O6jwaP_M"
  DRIVE_FOLDER_PROCESSANDO: "1kDD47j6SoEEstSff0B69fzMDM7xZ9oAa"
  DRIVE_FOLDER_PROCESSADO: "15af6f_TSsiYi6gBYxFNd9WVf8MXZSKLz"
  DRIVE_FOLDER_VALIDAR: "1qj1FZx_8ROjV5Hec-Jf__5Xg_kdVTWde"
  DRIVE_FOLDER_ERRO: "1oG5d4BtB2UGIPqYmur92wsq4T490tDmg"
