apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ia-automation-secrets
  namespace: monitoring
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-prod
  target:
    name: ia-automation-secrets
    creationPolicy: Owner
    template:
      data:
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        GEMINI_API_KEY: "{{ .GEMINI_API_KEY }}"
        WEB_SECRET: "{{ .WEB_SECRET }}"
        WEB_PASSWORD: "{{ .WEB_PASSWORD }}"
        N8N_API_KEY: "{{ .N8N_API_KEY }}"
        APP_MAIL_PASSWORD: "{{ .APP_MAIL_PASSWORD }}"
        GOOGLE_SA_JSON: "{{ .GOOGLE_SA_JSON | b64dec }}"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /ia-automation/POSTGRES_PASSWORD
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: /ia-automation/GEMINI_API_KEY
    - secretKey: WEB_SECRET
      remoteRef:
        key: /ia-automation/WEB_SECRET
    - secretKey: WEB_PASSWORD
      remoteRef:
        key: /ia-automation/WEB_PASSWORD
    - secretKey: N8N_API_KEY
      remoteRef:
        key: /ia-automation/N8N_API_KEY
    - secretKey: APP_MAIL_PASSWORD
      remoteRef:
        key: /ia-automation/APP_MAIL_PASSWORD
    - secretKey: GOOGLE_SA_JSON
      remoteRef:
        key: /ia-automation/GOOGLE_SA_JSON
