apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - imagepullsecret.yaml
  - pvc.yaml
  - postgres-init-configmap.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - prompts-configmap.yaml
  - worker-configmap.yaml
  - worker-deployment.yaml
  - worker-service.yaml
