apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ia-automation-postgres-data
  namespace: monitoring
spec:
  storageClassName: custom-local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ia-automation-worker-logs
  namespace: monitoring
spec:
  storageClassName: custom-local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
