apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: monitoring
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: WEBPASSWORD
            - name: FTLCONF_webserver_port
              value: "8080"
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          startupProbe:
            httpGet:
              path: /admin/
              port: 8080
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /admin/
              port: 8080
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /admin/
              port: 8080
            initialDelaySeconds: 120
          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
