apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: monitoring
spec:
  storageClassName: custom-local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: monitoring
spec:
  storageClassName: custom-local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
