apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: monitoring
spec:
  selector:
    app: pihole
  ports:
    - name: http
      port: 8080
      targetPort: web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web-nodeport
  namespace: monitoring
spec:
  selector:
    app: pihole
  ports:
    - name: http
      port: 8080
      targetPort: web
      nodePort: 30081
  type: NodePort
