apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-victoria
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/victoria-metrics-data
