apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-data
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-victoria
