apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-data
  namespace: monitoring
spec:
  storageClassName: custom-local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
