apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/instance: victoriametrics
  ports:
    - name: http
      port: 8428
      targetPort: 8428
  type: ClusterIP
