apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-iii-secrets
  namespace: finance
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-prod
  target:
    name: firefly-iii-secrets
    creationPolicy: Owner
    template:
      data:
        APP_KEY: "{{ .APP_KEY }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        POSTGRES_PASSWORD: "{{ .DB_PASSWORD }}"
        POSTGRES_USER: "firefly"
        POSTGRES_DB: "firefly"
        DBNAME: "firefly"
        DBUSER: "firefly"
        TZ: "America/Sao_Paulo"
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: /firefly-iii/APP_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /firefly-iii/DB_PASSWORD
