apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-iii-secrets
  namespace: finance
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-prod
  target:
    name: firefly-iii-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: /firefly-iii/APP_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /firefly-iii/DB_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /firefly-iii/DB_PASSWORD
