apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-prod
  target:
    name: n8n-secrets
    creationPolicy: Owner
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: /n8n/N8N_ENCRYPTION_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /n8n/POSTGRES_PASSWORD
