apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  storageClassName: custom-local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-postgres-data
  namespace: n8n
spec:
  storageClassName: custom-local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
