apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zuno-app-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-zuno-app-dev
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: POSTGRES_PASSWORD
    - secretKey: SPRING_JWT_SECRET
      remoteRef:
        key: SPRING_JWT_SECRET
