apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zuno-app-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-zuno-app-dev
  data:
    - secretKey: postgres-password
      remoteRef:
        key: POSTGRES_PASSWORD
