apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - nginx-config.yaml
  - externalsecret.yaml
images:
  - name: ojasonw/joga-together-web
    newTag: v1.0.5
  - name: ojasonw/my-java-app
    newTag: v1.0.11
