apiVersion: v1
kind: Service
metadata:
  name: joga-together
spec:
  selector:
    app: joga-together-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: joga-together-frontend
spec:
  selector:
    app: joga-together-frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
