apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-config
  namespace: monitoring
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-prod-cloudflare
  target:
    name: pve-config
    creationPolicy: Owner
  data:
    - secretKey: pve.yml
      remoteRef:
        key: /pve-exporter/PVE_YML
