apiVersion: v1
kind: Secret
metadata:
    name: pve-config
    namespace: monitoring
type: Opaque
stringData:
    pve.yml: ENC[AES256_GCM,data:FWzt91IpBpd6mqUbp6wnbVa00PrVSooqpY410wjbjjohNys7Au6mXj6yP6LaF2Qra65MGmGb9yKzx0qeH7eMa+SNd6lqo3rjCZPfi/5S0tYqpV49YFi2J5YleJUiDj9qt8mLKXdHsZnP9Tlx6ETL3mm6i6LYh7qMogDSRIXV0KwIzi0fDu1j,iv:cA4C1BPerAy3uTmt0WPYOMC8XgyRrM5DcBikvLUMyWI=,tag:B/O0if+1qj8TByZ/SwWn8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fweajqxcxfygfurlpg6r9myu25fcrha0xxtaujwywskkaryewyas8hww9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ0NObHY3S2JyN3B5TFdm
            V01Jc1RNWHlsb0M4NkMzYzIwRFNGTTVWb1JvCk9NaVRkdUhaVXZuejBpTk9NNUR0
            WTRkZVh2cTNiWkNGODREc09YVW14ZVkKLS0tIEY4WkhMdUg5bzJqRHRGMHQzZm9r
            SXJPTjdCMjNnSFNpMEo1S0c4Yk5KWnMKBsqF+y+cl/iIGm2b1A14lDijzOTUmb0v
            Mq+cTUy3XwG/7dOpfPRTvwjqtOJTfM9+GjkqMw4O9y7xpeW2xaH2Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T15:28:01Z"
    mac: ENC[AES256_GCM,data:t6HjG3Tm/RMtHDRYmjZZG6a6gaf9TFHopSf8g+1IRa71abZoBFhLlQ+cEPpAYRWpL0uf+rI9UwoiDGT1CnDVnokpmcAOb+D5PVrTWpHqrnN21hoOQ1KUt0rn7xkhLVh83CDkSUlqL5b/hVRgDot9JOntjkaBr45sHDDEgVCeKo0=,iv:gcz7D1A6jo9TGLsVtK3P4ur87d2yP/kVh6iIzC872LQ=,tag:TlG0R/Xjan5yhn5PsKrHSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
