apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-iii
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://firefly-iii.github.io/kubernetes/
      chart: firefly-iii-stack
      targetRevision: "0.9.2"
      helm:
        releaseName: firefly-iii
        valueFiles:
          - $valuesRepo/infra/firefly-iii/base/values.yaml
    - repoURL: https://github.com/ojasonw/homelab-gitops.git
      targetRevision: main
      ref: valuesRepo
  destination:
    server: https://kubernetes.default.svc
    namespace: finance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
