apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: joga-together
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: prod
            namespace: joga-together
          - env: dev
            namespace: joga-together-dev
  template:
    metadata:
      name: 'joga-together-{{.env}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/ojasonw/homelab-gitops.git
        targetRevision: main
        path: 'infra/joga-together/overlays/{{.env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
