apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docs-analitics-secrets
  namespace: docs-analitics
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-prod
  target:
    name: docs-analitics-secrets
    creationPolicy: Owner
    template:
      data:
        GOOGLE_SA_JSON: "{{ .GOOGLE_SA_JSON | b64dec }}"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /docs-analitics/POSTGRES_PASSWORD
    - secretKey: WORKER_SECRET
      remoteRef:
        key: /docs-analitics/WORKER_SECRET
    - secretKey: GOOGLE_SA_JSON
      remoteRef:
        key: /docs-analitics/GOOGLE_SA_JSON
