apiVersion: apps/v1
kind: Deployment
metadata:
  name: artjason-site
  namespace: artjason-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: artjason-site
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: artjason-site
    spec:
      containers:
        - name: nginx
          image: ojasonw/web-site:v1.0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
